<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#What-is-PyTorch?" data-toc-modified-id="What-is-PyTorch?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>What is PyTorch?</a></span></li></ul></div>

What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.0919e-39, 1.0102e-38, 8.9082e-39],
        [8.4489e-39, 1.0102e-38, 1.0561e-38],
        [1.0286e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[1.5719e-01, 2.9356e-01, 3.9174e-01],
        [1.0983e-01, 4.4159e-01, 7.8441e-01],
        [6.4857e-01, 8.4014e-01, 2.4516e-01],
        [9.9383e-01, 7.2924e-01, 1.8311e-04],
        [2.7815e-01, 6.1705e-01, 7.0814e-01]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3298, -1.4255, -1.4198],
        [-0.5724, -0.2992, -0.9432],
        [-0.7618,  1.2947,  0.5492],
        [ 1.3782, -1.7633, -1.3100],
        [-0.8811, -0.1592,  0.4112]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.0354, -1.2731, -0.5049],
        [-0.4474, -0.1480, -0.6079],
        [-0.1096,  1.7999,  1.0281],
        [ 1.6775, -1.7208, -0.9367],
        [-0.0299,  0.3553,  0.4804]])


Addition: syntax 2



In [10]:
print(torch.add(x, y))

tensor([[ 0.0354, -1.2731, -0.5049],
        [-0.4474, -0.1480, -0.6079],
        [-0.1096,  1.7999,  1.0281],
        [ 1.6775, -1.7208, -0.9367],
        [-0.0299,  0.3553,  0.4804]])


Addition: providing an output tensor as argument



In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.0354, -1.2731, -0.5049],
        [-0.4474, -0.1480, -0.6079],
        [-0.1096,  1.7999,  1.0281],
        [ 1.6775, -1.7208, -0.9367],
        [-0.0299,  0.3553,  0.4804]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an `_`.
    For example: `x.copy_(y)`, `x.t_()`, will change `x`.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



Addition: in-place



In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.0354, -1.2731, -0.5049],
        [-0.4474, -0.1480, -0.6079],
        [-0.1096,  1.7999,  1.0281],
        [ 1.6775, -1.7208, -0.9367],
        [-0.0299,  0.3553,  0.4804]])


In [13]:
print(x[:, 1])

tensor([-1.4255, -0.2992,  1.2947, -1.7633, -0.1592])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [3]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [4]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9414])
1.9414100646972656


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [5]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [6]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [7]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [8]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [9]:
import torch

torch.cuda.is_available()

True

In [10]:

# We will use ``torch.device`` objects to move tensors in and out of GPU
device = torch.device("cuda")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.9414], device='cuda:0')
tensor([2.9414], dtype=torch.float64)


In [11]:
z = np.zeros(int(1e9),dtype = 'f')
z[:] = np.random.randn(*x.shape)

In [12]:
z.nbytes

4000000000

In [13]:
ztorch = torch.from_numpy(z)

In [14]:
zgpu = ztorch.to(device,torch.float32)

In [15]:
ztorch[0] = 10

In [16]:
print(zgpu)

tensor([-0.3663, -0.3663, -0.3663,  ..., -0.3663, -0.3663, -0.3663],
       device='cuda:0')


In [17]:
zgpu[0]

tensor(-0.3663, device='cuda:0')