<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Neural-Networks" data-toc-modified-id="Neural-Networks-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Neural Networks</a></span></li></ul></div>

Neural Networks
===============

Neural networks can be constructed using the ``torch.nn`` package.

Now that you had a glimpse of ``autograd``, ``nn`` depends on
``autograd`` to define models and differentiate them.
An ``nn.Module`` contains layers, and a method ``forward(input)``\ that
returns the ``output``.

For example, look at this network that classifies digit images:

![convnet](../_static/img/mnist.png)

It is a simple feed-forward network. It takes the input, feeds it
through several layers one after the other, and then finally gives the
output.

A typical training procedure for a neural network is as follows:

- Define the neural network that has some learnable parameters (or
  weights)

- Iterate over a dataset of inputs

- Process input through the network

- Compute the loss (how far is the output from being correct)

- Propagate gradients back into the network’s parameters

- Update the weights of the network, typically using a simple update rule:
  ``weight = weight - learning_rate * gradient``

Define the network
------------------

Let’s define this network:

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


You just have to define the ``forward`` function, and the ``backward``
function (where gradients are computed) is automatically defined for you
using ``autograd``.
You can use any of the Tensor operations in the ``forward`` function.

The learnable parameters of a model are returned by ``net.parameters()``



In [4]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

[Parameter containing:
tensor([[[[ 6.7859e-02, -1.9005e-01,  1.8810e-01,  1.2923e-02,  8.9450e-03],
          [-3.2996e-02, -1.3114e-01,  1.1513e-01, -1.0494e-01,  7.1926e-02],
          [-8.4603e-02, -1.6450e-01,  5.2596e-02, -6.8345e-02, -1.5887e-01],
          [ 1.4162e-01,  6.5854e-02, -4.4675e-02,  1.1221e-01,  1.6472e-02],
          [-9.0864e-02, -1.1963e-01,  1.6023e-02,  1.9505e-01, -5.3095e-02]]],


        [[[ 1.6647e-01,  1.8772e-01,  4.1453e-02, -1.0453e-01, -6.1271e-02],
          [ 1.9138e-01, -3.7036e-02, -1.8216e-02, -8.0275e-02, -3.9518e-02],
          [ 1.1836e-01,  1.4361e-01,  3.8874e-02,  1.1272e-01,  3.6754e-02],
          [ 1.7342e-02,  1.8355e-01, -6.9731e-02,  1.8142e-03,  4.8517e-02],
          [ 1.3354e-01, -1.3123e-01, -9.5407e-02, -1.7106e-01, -1.1009e-01]]],


        [[[ 1.8091e-01, -1.5856e-01,  1.5622e-01,  5.2095e-02,  1.5880e-01],
          [ 1.8159e-01, -1.3252e-01,  1.1634e-01,  1.5389e-01, -1.6238e-01],
          [-1.7970e-01, -4.8288e-02,  1.9923e

Let try a random 32x32 input
Note: Expected input size to this net(LeNet) is 32x32. To use this net on
MNIST dataset, please resize the images from the dataset to 32x32.



In [5]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0649, -0.1442,  0.0727, -0.0277,  0.0536,  0.0148,  0.0673, -0.0857,
          0.0316, -0.0228]], grad_fn=<AddmmBackward>)


Zero the gradient buffers of all parameters and backprops with random
gradients:



In [6]:
net.zero_grad()
out.backward(torch.randn(1, 10))

<div class="alert alert-info"><h4>Note</h4><p>``torch.nn`` only supports mini-batches. The entire ``torch.nn``
    package only supports inputs that are a mini-batch of samples, and not
    a single sample.

    For example, ``nn.Conv2d`` will take in a 4D Tensor of
    ``nSamples x nChannels x Height x Width``.

    If you have a single sample, just use ``input.unsqueeze(0)`` to add
    a fake batch dimension.
</p></div>

Before proceeding further, let's recap all the classes you’ve seen so far.

**Recap:**
  -  ``torch.Tensor`` - A *multi-dimensional array* with support for autograd
     operations like ``backward()``. Also *holds the gradient* w.r.t. the
     tensor.
  -  ``nn.Module`` - Neural network module. *Convenient way of
     encapsulating parameters*, with helpers for moving them to GPU,
     exporting, loading, etc.
  -  ``nn.Parameter`` - A kind of Tensor, that is *automatically
     registered as a parameter when assigned as an attribute to a*
     ``Module``.
  -  ``autograd.Function`` - Implements *forward and backward definitions
     of an autograd operation*. Every ``Tensor`` operation, creates at
     least a single ``Function`` node, that connects to functions that
     created a ``Tensor`` and *encodes its history*.

**At this point, we covered:**
  -  Defining a neural network
  -  Processing inputs and calling backward

**Still Left:**
  -  Computing the loss
  -  Updating the weights of the network

Loss Function
-------------
A loss function takes the (output, target) pair of inputs, and computes a
value that estimates how far away the output is from the target.

There are several different
`loss functions <https://pytorch.org/docs/nn.html#loss-functions>`_ under the
nn package .
A simple loss is: ``nn.MSELoss`` which computes the mean-squared error
between the input and the target.

For example:

In [8]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
print(target)
target = target.view(1, -1)  # make it the same shape as output
print(target)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor([ 0.3441, -0.6741, -1.0023, -0.7223,  0.8283, -0.5215,  1.7272,  0.1900,
        -0.4528, -0.8494])
tensor([[ 0.3441, -0.6741, -1.0023, -0.7223,  0.8283, -0.5215,  1.7272,  0.1900,
         -0.4528, -0.8494]])
tensor(0.6634, grad_fn=<MseLossBackward>)


Now, if you follow ``loss`` in the backward direction, using its
``.grad_fn`` attribute, you will see a graph of computations that looks
like this:

::

    input -> conv2d -> relu -> maxpool2d -> conv2d -> relu -> maxpool2d
          -> view -> linear -> relu -> linear -> relu -> linear
          -> MSELoss
          -> loss

So, when we call ``loss.backward()``, the whole graph is differentiated
w.r.t. the loss, and all Tensors in the graph that has ``requires_grad=True``
will have their ``.grad`` Tensor accumulated with the gradient.

For illustration, let us follow a few steps backward:

In [9]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

Backprop
--------
To backpropagate the error all we have to do is to ``loss.backward()``.
You need to clear the existing gradients though, else gradients will be
accumulated to existing gradients.


Now we shall call ``loss.backward()``, and have a look at conv1's bias
gradients before and after the backward.



In [10]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0152,  0.0101,  0.0002,  0.0037, -0.0074, -0.0026])


Now, we have seen how to use loss functions.

**Read Later:**

  The neural network package contains various modules and loss functions
  that form the building blocks of deep neural networks. A full list with
  documentation is [here](https://pytorch.org/docs/nn).

**The only thing left to learn is:**

  - Updating the weights of the network

Update the weights
------------------
The simplest update rule used in practice is the Stochastic Gradient
Descent (SGD):

     ``weight = weight - learning_rate * gradient``

We can implement this using simple python code:

```python
    learning_rate = 0.01
    for f in net.parameters():
        f.data.sub_(f.grad.data * learning_rate)
```

However, as you use neural networks, you want to use various different
update rules such as SGD, Nesterov-SGD, Adam, RMSProp, etc.
To enable this, we built a small package: ``torch.optim`` that
implements all these methods. Using it is very simple:

In [11]:
f1 = next(net.parameters())
f1

Parameter containing:
tensor([[[[ 6.7859e-02, -1.9005e-01,  1.8810e-01,  1.2923e-02,  8.9450e-03],
          [-3.2996e-02, -1.3114e-01,  1.1513e-01, -1.0494e-01,  7.1926e-02],
          [-8.4603e-02, -1.6450e-01,  5.2596e-02, -6.8345e-02, -1.5887e-01],
          [ 1.4162e-01,  6.5854e-02, -4.4675e-02,  1.1221e-01,  1.6472e-02],
          [-9.0864e-02, -1.1963e-01,  1.6023e-02,  1.9505e-01, -5.3095e-02]]],


        [[[ 1.6647e-01,  1.8772e-01,  4.1453e-02, -1.0453e-01, -6.1271e-02],
          [ 1.9138e-01, -3.7036e-02, -1.8216e-02, -8.0275e-02, -3.9518e-02],
          [ 1.1836e-01,  1.4361e-01,  3.8874e-02,  1.1272e-01,  3.6754e-02],
          [ 1.7342e-02,  1.8355e-01, -6.9731e-02,  1.8142e-03,  4.8517e-02],
          [ 1.3354e-01, -1.3123e-01, -9.5407e-02, -1.7106e-01, -1.1009e-01]]],


        [[[ 1.8091e-01, -1.5856e-01,  1.5622e-01,  5.2095e-02,  1.5880e-01],
          [ 1.8159e-01, -1.3252e-01,  1.1634e-01,  1.5389e-01, -1.6238e-01],
          [-1.7970e-01, -4.8288e-02,  1.9923e-

In [ ]:
f1.data.sub_(f1.grad * 0.01)
f1

In [12]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

.. Note::

      Observe how gradient buffers had to be manually set to zero using
      ``optimizer.zero_grad()``. This is because gradients are accumulated
      as explained in `Backprop`_ section.

